- name: Allow root to login
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  tasks:
  - name: Replace the auth key file of root user
    copy:
      remote_src: yes
      src: /home/ubuntu/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
  vars:
    ansible_ssh_private_key_file: '/home/koshik/.ssh/consensolabs-admin.pem'
  